spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
rabbitmq.producer.queuename: ${RABBITMQ_QUEUENAME}
queue.write.rate: ${QUEUE_WRITE_RATE}
